spring.application.name=ApiGateway

spring.cloud.gateway.server.webmvc.routes[0].id=Hello
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates=Path=/product/**

spring.cloud.gateway.server.webmvc.routes[1].id=CartService
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[1].predicates=Path=/cart/**